/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2016-05-09 16:16:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.webpage.weixin.cms;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class cmsArticle_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/tld/easyui.tld", Long.valueOf(1462721646514L));
    _jspx_dependants.put("/context/mytags.jsp", Long.valueOf(1462721497509L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fformvalid_0026_005fusePlugin_005flayout_005fformid_005fdialog_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fdictSelect_0026_005ffield_005fdictText_005fdictTable_005fdictField_005fdefaultVal_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fformvalid_0026_005fusePlugin_005flayout_005fformid_005fdialog_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fdictSelect_0026_005ffield_005fdictText_005fdictTable_005fdictField_005fdefaultVal_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody.release();
    _005fjspx_005ftagPool_005ft_005fformvalid_0026_005fusePlugin_005flayout_005fformid_005fdialog_005faction.release();
    _005fjspx_005ftagPool_005ft_005fdictSelect_0026_005ffield_005fdictText_005fdictTable_005fdictField_005fdefaultVal_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path;

      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /context/mytags.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("webRoot");
      // /context/mytags.jsp(9,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(basePath);
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write(" <head>\n");
      out.write("  <title>信息管理</title>\n");
      out.write("  ");
      if (_jspx_meth_t_005fbase_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"plug-in/weixin/css/appmsg_edit.css\" />\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"plug-in/weixin/css/jquery.fileupload.css\" />\n");
      out.write("  <link type=\"text/css\" rel=\"stylesheet\" href=\"plug-in/bootstrap/css/bootstrap.min.css\" />\n");
      out.write("  <script type=\"text/javascript\" src=\"plug-in/ckfinder/ckfinder.js\"></script>\n");
      out.write("  \n");
      out.write("  <!--fileupload-->\n");
      out.write("  <script type=\"text/javascript\" src=\"plug-in/weixin/js/vendor/jquery.ui.widget.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"plug-in/weixin/js/load-image.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"plug-in/weixin/js/jquery.fileupload.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"plug-in/weixin/js/jquery.fileupload-process.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"plug-in/weixin/js/jquery.fileupload-image.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"plug-in/weixin/js/jquery.iframe-transport.js\"></script>\n");
      out.write("  <!--UEditor-->\n");
      out.write("  <script type=\"text/javascript\"  charset=\"utf-8\" src=\"plug-in/ueditor/ueditor.config.js\"></script>\n");
      out.write("  <script type=\"text/javascript\"  charset=\"utf-8\" src=\"plug-in/ueditor/ueditor.all.min.js\"></script>\n");
      out.write("    \n");
      out.write("  <!--建议手动加在语言，避免在ie下有时因为加载语言失败导致编辑器加载失败-->\n");
      out.write("  <!--这里加载的语言文件会覆盖你在配置项目里添加的语言类型，比如你在配置项目里配置的是英文，这里加载的中文，那最后就是中文-->\n");
      out.write("  <script type=\"text/javascript\" charset=\"utf-8\" src=\"plug-in/ueditor/lang/zh-cn/zh-cn.js\"></script>\n");
      out.write("  <script type=\"text/javascript\">\n");
      out.write("  //编写自定义JS代码\n");
      out.write("  /*jslint unparam: true, regexp: true */\n");
      out.write("  /*global window, $ */\n");
      out.write("  $(function () {\n");
      out.write("      'use strict';\n");
      out.write("      // Change this to the location of your server-side upload handler:\n");
      out.write("      var url = 'weixinArticleController.do?upload',\n");
      out.write("          uploadButton = $('<button/>')\n");
      out.write("              .addClass('btn btn-primary')\n");
      out.write("              .prop('disabled', true)\n");
      out.write("              .text('上传中...')\n");
      out.write("              .on('click', function () {\n");
      out.write("                  var $this = $(this), data = $this.data();\n");
      out.write("                  $this.off('click').text('正在上传...').on('click', function () {\n");
      out.write("                          $this.remove();\n");
      out.write("                          data.abort();\n");
      out.write("                  });\n");
      out.write("                  data.submit().always(function () {\n");
      out.write("                      $this.remove();\n");
      out.write("                  });\n");
      out.write("              });\n");
      out.write("      $('#fileupload').fileupload({\n");
      out.write("          url: url,\n");
      out.write("          dataType: 'json',\n");
      out.write("          autoUpload: false,\n");
      out.write("          acceptFileTypes: /(\\.|\\/)(gif|jpe?g|png)$/i,\n");
      out.write("          maxFileSize: 2000000, // 2 MB\n");
      out.write("          disableImageResize: /Android(?!.*Chrome)|Opera/\n");
      out.write("              .test(window.navigator.userAgent),\n");
      out.write("          previewMaxWidth: 290,\n");
      out.write("          previewMaxHeight: 160,\n");
      out.write("          previewCrop: true\n");
      out.write("      }).on('fileuploadadd', function (e, data) {\n");
      out.write("          $(\"#files\").text(\"\");\n");
      out.write("          data.context = $('<div/>').appendTo('#files');\n");
      out.write("          $.each(data.files, function (index, file) {\n");
      out.write("              //var node = $('<p/>').append($('<span/>').text(file.name));\n");
      out.write("              //fileupload\n");
      out.write("              var node = $('<p/>');\n");
      out.write("              if (!index) {\n");
      out.write("                  node.append('<br>').append(uploadButton.clone(true).data(data));\n");
      out.write("              }\n");
      out.write("              node.appendTo(data.context);\n");
      out.write("          });\n");
      out.write("      }).on('fileuploadprocessalways', function (e, data) {\n");
      out.write("          var index = data.index,\n");
      out.write("              file = data.files[index],\n");
      out.write("              node = $(data.context.children()[index]);\n");
      out.write("          if (file.preview) {\n");
      out.write("              node.prepend('<br>').prepend(file.preview);\n");
      out.write("          }\n");
      out.write("          if (file.error) {\n");
      out.write("              node\n");
      out.write("                  .append('<br>')\n");
      out.write("                  .append($('<span class=\"text-danger\"/>').text(file.error));\n");
      out.write("          }\n");
      out.write("          if (index + 1 === data.files.length) {\n");
      out.write("              data.context.find('button')\n");
      out.write("                  .text('上传')\n");
      out.write("                  .prop('disabled', !!data.files.error);\n");
      out.write("          }\n");
      out.write("      }).on('fileuploadprogressall', function (e, data) {\n");
      out.write("          var progress = parseInt(data.loaded / data.total * 100, 10);\n");
      out.write("          $('#progress .progress-bar').css(\n");
      out.write("              'width',\n");
      out.write("              progress + '%'\n");
      out.write("          );\n");
      out.write("      }).on('fileuploaddone', function (e, data) {\n");
      out.write("          console.info(data);\n");
      out.write("          var  file = data.files[0];\n");
      out.write("          //var delUrl = \"<a class=\\\"js_removeCover\\\" onclick=\\\"return false;\\\" href=\\\"javascript:void(0);\\\">删除</a>\";\n");
      out.write("          $(\"#imgName\").text(\"\").append(file.name);\n");
      out.write("          $(\"#imageName\").val(file.name);\n");
      out.write("          $(\"#progress\").hide();\n");
      out.write("  \t\tvar d =data.result;\n");
      out.write("  \t\tif (d.success) {\n");
      out.write("  \t\t\tvar link = $('<a>').attr('target', '_blank').prop('href', d.attributes.viewhref);\n");
      out.write("          \t$(data.context.children()[0]).wrap(link);\n");
      out.write("          \tconsole.info(d.attributes.viewhref);\n");
      out.write("          \t$(\"#imageHref\").val(d.attributes.url);\n");
      out.write("  \t\t}else{\n");
      out.write("  \t\t\tvar error = $('<span class=\"text-danger\"/>').text(d.msg);\n");
      out.write("              $(data.context.children()[0]).append('<br>').append(error);\n");
      out.write("  \t\t}\n");
      out.write("      }).on('fileuploadfail', function (e, data) {\n");
      out.write("          $.each(data.files, function (index, file) {\n");
      out.write("              var error = $('<span class=\"text-danger\"/>').text('File upload failed.');\n");
      out.write("              $(data.context.children()[index])\n");
      out.write("                  .append('<br>')\n");
      out.write("                  .append(error);\n");
      out.write("          });\n");
      out.write("      }).prop('disabled', !$.support.fileInput)\n");
      out.write("          .parent().addClass($.support.fileInput ? undefined : 'disabled');\n");
      out.write("      \n");
      out.write("      //编辑时初始化图片预览\n");
      out.write("      var name = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cmsArticlePage.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\", imageHref = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cmsArticlePage.imageHref}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\n");
      out.write("      if(name != \"\"){\n");
      out.write("          $(\"#imageTitle\").html(name);\n");
      out.write("      }\n");
      out.write("      if(imageHref != \"\"){\n");
      out.write("          $(\"#imageShow\").html('<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cmsArticlePage.imageHref}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" width=\"100%\" height=\"160\" />');\n");
      out.write("      }\n");
      out.write("  });\n");
      out.write("  function setimageTitle(obj){\n");
      out.write("\t  $(\"#imageTitle\").html($(obj).val());\n");
      out.write("  }\n");
      out.write("  </script>\n");
      out.write(" </head>\n");
      out.write(" <body>\n");
      out.write(" \t<div class=\"main_bd\">\n");
      out.write("\t\t<div class=\"media_preview_area\">\n");
      out.write("\t\t\t<div class=\"appmsg editing\">\n");
      out.write("\t\t\t\t<div class=\"appmsg_content\" id=\"js_appmsg_preview\">\n");
      out.write("\t\t\t\t\t\t<h4 class=\"appmsg_title\">\n");
      out.write("\t\t\t\t\t\t\t<a target=\"_blank\" href=\"javascript:void(0);\" onclick=\"return false;\" id=\"imageTitle\">标题</a>\n");
      out.write("\t\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t\t<div class=\"appmsg_info\">\n");
      out.write("\t\t\t\t\t\t\t<em class=\"appmsg_date\"></em>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"files\" class=\"files\">\n");
      out.write("\t\t\t\t\t\t\t<i class=\"appmsg_thumb default\" id=\"imageShow\">栏目图片</i>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t <div id=\"progress\" class=\"progress\">\n");
      out.write("\t\t\t\t\t        <div class=\"progress-bar progress-bar-success\"></div>\n");
      out.write("\t\t\t\t\t    </div>\n");
      out.write("\t\t\t\t\t\t<p class=\"appmsg_desc\"></p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write(" \t\t<div class=\"media_edit_area\" id=\"js_appmsg_editor\">\t\n");
      out.write("\t\t\t<div class=\"appmsg_editor\" style=\"margin-top: 0px;\">\n");
      out.write("\t\t \t\t<div class=\"inner\">\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_t_005fformvalid_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<i class=\"arrow arrow_out\" style=\"margin-top: 0px;\"></i>\n");
      out.write("\t\t\t\t<i class=\"arrow arrow_in\" style=\"margin-top: 0px;\"></i>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write(" </body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_t_005fbase_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:base
    org.jeecgframework.tag.core.easyui.BaseTag _jspx_th_t_005fbase_005f0 = (org.jeecgframework.tag.core.easyui.BaseTag) _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody.get(org.jeecgframework.tag.core.easyui.BaseTag.class);
    _jspx_th_t_005fbase_005f0.setPageContext(_jspx_page_context);
    _jspx_th_t_005fbase_005f0.setParent(null);
    // /webpage/weixin/cms/cmsArticle.jsp(7,2) name = type type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fbase_005f0.setType("jquery,easyui,tools,DatePicker");
    int _jspx_eval_t_005fbase_005f0 = _jspx_th_t_005fbase_005f0.doStartTag();
    if (_jspx_th_t_005fbase_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody.reuse(_jspx_th_t_005fbase_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ft_005fbase_0026_005ftype_005fnobody.reuse(_jspx_th_t_005fbase_005f0);
    return false;
  }

  private boolean _jspx_meth_t_005fformvalid_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:formvalid
    org.jeecgframework.tag.core.easyui.FormValidationTag _jspx_th_t_005fformvalid_005f0 = (org.jeecgframework.tag.core.easyui.FormValidationTag) _005fjspx_005ftagPool_005ft_005fformvalid_0026_005fusePlugin_005flayout_005fformid_005fdialog_005faction.get(org.jeecgframework.tag.core.easyui.FormValidationTag.class);
    _jspx_th_t_005fformvalid_005f0.setPageContext(_jspx_page_context);
    _jspx_th_t_005fformvalid_005f0.setParent(null);
    // /webpage/weixin/cms/cmsArticle.jsp(160,5) name = formid type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fformvalid_005f0.setFormid("formobj");
    // /webpage/weixin/cms/cmsArticle.jsp(160,5) name = dialog type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fformvalid_005f0.setDialog(true);
    // /webpage/weixin/cms/cmsArticle.jsp(160,5) name = usePlugin type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fformvalid_005f0.setUsePlugin("password");
    // /webpage/weixin/cms/cmsArticle.jsp(160,5) name = layout type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fformvalid_005f0.setLayout("table");
    // /webpage/weixin/cms/cmsArticle.jsp(160,5) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fformvalid_005f0.setAction("cmsArticleController.do?save");
    int _jspx_eval_t_005fformvalid_005f0 = _jspx_th_t_005fformvalid_005f0.doStartTag();
    if (_jspx_eval_t_005fformvalid_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t\t\t\t\t<input id=\"id\" name=\"id\" type=\"hidden\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cmsArticlePage.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\">\n");
        out.write("\t\t\t\t\t<input type=\"hidden\" name=\"accountid\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cmsArticlePage.accountid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\">\n");
        out.write("\t\t\t\t\t<input type=\"hidden\" name=\"imageName\" id=\"imageName\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cmsArticlePage.imageName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\">\n");
        out.write("\t\t\t\t\t<table cellpadding=\"0\" cellspacing=\"1\" class=\"formtable\">\n");
        out.write("\t\t\t\t\t\t<tr>\n");
        out.write("\t\t\t\t\t\t\t<td align=\"right\">\n");
        out.write("\t\t\t\t\t\t\t\t<label class=\"Validform_label\">\n");
        out.write("\t\t\t\t\t\t\t\t\t标题:\n");
        out.write("\t\t\t\t\t\t\t\t</label>\n");
        out.write("\t\t\t\t\t\t\t</td>\n");
        out.write("\t\t\t\t\t\t\t<td class=\"value\">\n");
        out.write("\t\t\t\t\t\t\t\t<input class=\"inputxt\" id=\"title\" name=\"title\" style=\"width: 300px\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cmsArticlePage.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\" datatype=\"*\" onblur=\"setimageTitle(this)\">\n");
        out.write("\t\t\t\t\t\t\t\t<span class=\"Validform_checktip\"></span>\n");
        out.write("\t\t\t\t\t\t\t\t<label class=\"Validform_label\" style=\"display: none;\">标题</label>\n");
        out.write("\t\t\t\t\t\t\t</td>\n");
        out.write("\t\t\t\t\t\t</tr>\n");
        out.write("\t\t\t\t\t\t<tr>\n");
        out.write("\t\t\t\t\t\t\t<td align=\"right\">\n");
        out.write("\t\t\t\t\t\t\t\t<label class=\"Validform_label\">\n");
        out.write("\t\t\t\t\t\t\t\t\t所属栏目:\n");
        out.write("\t\t\t\t\t\t\t\t</label>\n");
        out.write("\t\t\t\t\t\t\t</td>\n");
        out.write("\t\t\t\t\t\t\t<td class=\"value\">\n");
        out.write("\t\t\t\t\t\t\t\t");
        if (_jspx_meth_t_005fdictSelect_005f0(_jspx_th_t_005fformvalid_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t\t\t\t\t\t\t\t<span class=\"Validform_checktip\"></span>\n");
        out.write("\t\t\t\t\t\t\t\t<label class=\"Validform_label\" style=\"display: none;\">所属栏目</label>\n");
        out.write("\t\t\t\t\t\t\t</td>\n");
        out.write("\t\t\t\t\t\t</tr>\n");
        out.write("\t\t\t\t\t\t<tr>\n");
        out.write("\t\t\t\t\t\t\t<td align=\"right\">\n");
        out.write("\t\t\t\t\t\t\t\t<label class=\"Validform_label\">\n");
        out.write("\t\t\t\t\t\t\t\t\t上传图片:\n");
        out.write("\t\t\t\t\t\t\t\t</label>\n");
        out.write("\t\t\t\t\t\t\t</td>\n");
        out.write("\t\t\t\t\t\t\t<td class=\"value\">\n");
        out.write("\t\t\t\t\t\t\t\t<span class=\"btn btn-success fileinput-button\">\n");
        out.write("\t\t\t\t\t\t\t        <i class=\"glyphicon glyphicon-plus\"></i>\n");
        out.write("\t\t\t\t\t\t\t        <span>浏览</span>\n");
        out.write("\t\t\t\t\t\t\t        <!-- The file input field used as target for the file upload widget -->\n");
        out.write("\t\t\t\t\t\t\t        <input id=\"fileupload\" type=\"file\" name=\"files[]\" multiple>\n");
        out.write("\t\t\t\t\t\t\t    </span>\n");
        out.write("\t\t\t\t\t\t\t    <input id=\"imageHref\" name=\"imageHref\" type=\"hidden\" nullmsg=\"请添加图片\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cmsArticlePage.imageHref}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\">\n");
        out.write("\t\t\t\t\t\t\t    <span id=\"imgName\"></span> \n");
        out.write("\t\t\t\t\t\t\t\t<span class=\"Validform_checktip\"></span>\n");
        out.write("\t\t\t\t\t\t\t\t<label class=\"Validform_label\" style=\"display: none;\">图片链接</label>\n");
        out.write("\t\t\t\t\t\t\t</td>\n");
        out.write("\t\t\t\t\t\t</tr>\n");
        out.write("\t\t\t\t\t\t<tr>\n");
        out.write("\t\t\t\t\t\t\t<td align=\"right\">\n");
        out.write("\t\t\t\t\t\t\t\t<label class=\"Validform_label\">\n");
        out.write("\t\t\t\t\t\t\t\t\t摘要:\n");
        out.write("\t\t\t\t\t\t\t\t</label>\n");
        out.write("\t\t\t\t\t\t\t</td>\n");
        out.write("\t\t\t\t\t\t\t<td class=\"value\">\n");
        out.write("\t\t\t\t\t\t\t\t<textarea class=\"inputxt\" id=\"summary\" name=\"summary\" style=\"width: 300px\" datatype=\"*\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cmsArticlePage.summary}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</textarea>\n");
        out.write("\t\t\t\t\t\t\t\t<span class=\"Validform_checktip\"></span>\n");
        out.write("\t\t\t\t\t\t\t\t<label class=\"Validform_label\" style=\"display: none;\">摘要</label>\n");
        out.write("\t\t\t\t\t\t\t</td>\n");
        out.write("\t\t\t\t\t\t</tr>\n");
        out.write("\t\t\t\t\t\t<tr>\n");
        out.write("\t\t\t\t\t\t\t<td align=\"right\">\n");
        out.write("\t\t\t\t\t\t\t\t<label class=\"Validform_label\">\n");
        out.write("\t\t\t\t\t\t\t\t\t正文:\n");
        out.write("\t\t\t\t\t\t\t\t</label>\n");
        out.write("\t\t\t\t\t\t\t</td>\n");
        out.write("\t\t\t\t\t\t\t<td class=\"value\">\n");
        out.write("\t\t\t\t\t\t\t\t <textarea name=\"content\" id=\"content\" style=\"width: 350px;height:300px\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cmsArticlePage.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</textarea>\n");
        out.write("\t\t\t\t\t\t\t    <script type=\"text/javascript\">\n");
        out.write("\t\t\t\t\t\t\t        var editor = UE.getEditor('content');\n");
        out.write("\t\t\t\t\t\t\t    </script>\n");
        out.write("\t\t\t\t\t\t\t</td>\n");
        out.write("\t\t\t\t\t\t</tr>\n");
        out.write("\t\t\t\t\t</table>\n");
        out.write("\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_t_005fformvalid_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_t_005fformvalid_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ft_005fformvalid_0026_005fusePlugin_005flayout_005fformid_005fdialog_005faction.reuse(_jspx_th_t_005fformvalid_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ft_005fformvalid_0026_005fusePlugin_005flayout_005fformid_005fdialog_005faction.reuse(_jspx_th_t_005fformvalid_005f0);
    return false;
  }

  private boolean _jspx_meth_t_005fdictSelect_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005fformvalid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:dictSelect
    org.jeecgframework.tag.core.easyui.DictSelectTag _jspx_th_t_005fdictSelect_005f0 = (org.jeecgframework.tag.core.easyui.DictSelectTag) _005fjspx_005ftagPool_005ft_005fdictSelect_0026_005ffield_005fdictText_005fdictTable_005fdictField_005fdefaultVal_005fnobody.get(org.jeecgframework.tag.core.easyui.DictSelectTag.class);
    _jspx_th_t_005fdictSelect_005f0.setPageContext(_jspx_page_context);
    _jspx_th_t_005fdictSelect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005fformvalid_005f0);
    // /webpage/weixin/cms/cmsArticle.jsp(184,8) name = field type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fdictSelect_005f0.setField("columnId");
    // /webpage/weixin/cms/cmsArticle.jsp(184,8) name = dictTable type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fdictSelect_005f0.setDictTable((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("weixin_cms_menu where accountid='${sessionScope.WEIXIN_ACCOUNT.id}'", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    // /webpage/weixin/cms/cmsArticle.jsp(184,8) name = dictField type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fdictSelect_005f0.setDictField("id");
    // /webpage/weixin/cms/cmsArticle.jsp(184,8) name = dictText type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fdictSelect_005f0.setDictText("name");
    // /webpage/weixin/cms/cmsArticle.jsp(184,8) name = defaultVal type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fdictSelect_005f0.setDefaultVal((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cmsArticlePage.columnId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_t_005fdictSelect_005f0 = _jspx_th_t_005fdictSelect_005f0.doStartTag();
    if (_jspx_th_t_005fdictSelect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ft_005fdictSelect_0026_005ffield_005fdictText_005fdictTable_005fdictField_005fdefaultVal_005fnobody.reuse(_jspx_th_t_005fdictSelect_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ft_005fdictSelect_0026_005ffield_005fdictText_005fdictTable_005fdictField_005fdefaultVal_005fnobody.reuse(_jspx_th_t_005fdictSelect_005f0);
    return false;
  }
}
